import { Platform } from "react-native";
import { Dimensions } from "react-native";
import { StyleSheet } from "react-native";

const isIOS = Platform.OS === "ios";
const { width, height } = Dimensions.get("window");
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  noInternetContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  noInternetIcon: {
    marginBottom: 24,
  },
  noInternetTitle: {
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 12,
    textAlign: "center",
  },
  noInternetText: {
    fontSize: 16,
    textAlign: "center",
    marginBottom: 32,
    lineHeight: 24,
  },
  noInternetButtons: {
    width: "100%",
    gap: 12,
    marginBottom: 24,
  },
  noInternetButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
    borderRadius: 14,
    gap: 10,
    width: "100%",
  },
  noInternetButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  noInternetButtonSecondary: {
    padding: 18,
    borderRadius: 14,
    width: "100%",
    alignItems: "center",
    borderWidth: 1,
  },
  noInternetButtonTextSecondary: {
    fontSize: 16,
    fontWeight: "600",
  },
  offlineDataButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderRadius: 12,
    gap: 8,
    marginTop: 20,
  },
  offlineDataText: {
    fontSize: 14,
    fontWeight: "500",
  },
  introScrollView: {
    flex: 1,
  },
  introScrollContent: {
    flexGrow: 1,
    justifyContent: "center",
  },
  introContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  introContent: {
    alignItems: "center",
    width: "100%",
    maxWidth: 400,
  },
  introIconContainer: {
    marginBottom: 32,
    position: "relative",
  },
  introIcon: {
    opacity: 0.9,
  },
  introIconGlow: {
    position: "absolute",
    top: -10,
    left: -10,
    right: -10,
    bottom: -10,
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    borderRadius: 60,
  },
  introTitle: {
    fontSize: 36,
    fontWeight: "800",
    marginBottom: 12,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  introSubtitle: {
    fontSize: 17,
    marginBottom: 32,
    textAlign: "center",
    lineHeight: 24,
    fontWeight: "400",
  },
  offlineWarning: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    marginBottom: 24,
    gap: 8,
    alignSelf: "center",
  },
  offlineWarningText: {
    fontSize: 14,
    fontWeight: "600",
  },
  introFeatures: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 24,
    marginBottom: 32,
  },
  featureItem: {
    alignItems: "center",
    gap: 8,
  },
  featureText: {
    fontSize: 14,
    fontWeight: "500",
  },
  introButtons: {
    width: "100%",
    gap: 20,
    marginBottom: 40,
  },
  introButtonPrimary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    borderRadius: 14,
    gap: 12,
  },
  introButtonPrimaryText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "600",
  },
  orContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginVertical: 8,
  },
  orLine: {
    flex: 1,
    height: 1,
  },
  orText: {
    fontSize: 15,
    fontWeight: "500",
  },
  searchIntroSection: {
    width: "100%",
    gap: 8,
  },
  searchLabel: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  searchIntroContainer: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  searchIntroInput: {
    flex: 1,
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 18,
    fontSize: 17,
    fontWeight: "400",
    borderWidth: 1,
  },
  searchIntroButton: {
    width: 60,
    height: 60,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  searchHistorySection: {
    width: "100%",
    marginTop: 16,
  },
  searchHistoryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  searchHistoryTitle: {
    fontSize: 16,
    fontWeight: "600",
  },
  clearHistoryText: {
    fontSize: 14,
    fontWeight: "500",
  },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    marginRight: 8,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.1)",
  },
  historyText: {
    fontSize: 14,
    fontWeight: "500",
  },
  introHint: {
    fontSize: 15,
    textAlign: "center",
    lineHeight: 22,
    fontWeight: "400",
    marginTop: 24,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  loadingContent: {
    marginBottom: 32,
  },
  loadingText: {
    fontSize: 18,
    marginBottom: 8,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  loadingSubtext: {
    fontSize: 14,
    marginBottom: 24,
    fontWeight: "400",
  },
  loadingProgress: {
    width: "60%",
    height: 4,
    backgroundColor: "rgba(0,0,0,0.1)",
    borderRadius: 2,
    overflow: "hidden",
  },
  loadingProgressBar: {
    height: "100%",
    borderRadius: 2,
  },
  background: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  weatherContainer: {
    flex: 1,
  },
  header: {
    paddingTop: isIOS ? 60 : 40,
    paddingHorizontal: 20,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  headerInfo: {
    alignItems: "center",
    flex: 1,
    marginHorizontal: 12,
  },
  timeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  timeIcon: {
    marginRight: 6,
  },
  currentTime: {
    fontSize: 17,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  lastUpdate: {
    fontSize: 12,
    fontWeight: "400",
    marginBottom: 4,
  },
  headerRight: {
    flexDirection: "row",
  },
  headerButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
  },
  networkWarning: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: "rgba(245, 158, 11, 0.1)",
  },
  networkWarningText: {
    fontSize: 11,
    fontWeight: "600",
  },
  searchHistoryDropdown: {
    position: "absolute",
    top: 120,
    left: 20,
    right: 20,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    zIndex: 1000,
  },
  searchHistoryDropdownHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  searchHistoryDropdownTitle: {
    fontSize: 14,
    fontWeight: "600",
  },
  searchHistoryItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
  },
  searchHistoryText: {
    flex: 1,
    marginHorizontal: 12,
    fontSize: 15,
    fontWeight: "500",
  },
  searchSection: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  searchContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    fontWeight: "400",
    paddingVertical: 10,
  },
  headerActions: {
    flexDirection: "row",
  },
  refreshButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
  },
  locationButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  currentWeatherCard: {
    borderRadius: 24,
    padding: 24,
    marginTop: 20,
    marginBottom: 24,
    borderWidth: 1,
  },
  cityHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
    gap: 8,
  },
  cityName: {
    fontSize: 32,
    fontWeight: "800",
    textAlign: "center",
    letterSpacing: -0.5,
  },
  currentDate: {
    fontSize: 17,
    textAlign: "center",
    marginBottom: 24,
    fontWeight: "400",
  },
  tempSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  weatherIcon: {
    width: 140,
    height: 140,
    marginRight: -20,
  },
  tempInfo: {
    alignItems: "flex-start",
  },
  currentTemp: {
    fontSize: 72,
    fontWeight: "300",
    letterSpacing: -2,
    lineHeight: 72,
  },
  feelsLike: {
    fontSize: 16,
    fontWeight: "500",
    marginTop: -8,
    marginBottom: 12,
  },
  tempRangeCurrent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  tempRangeItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  tempRangeText: {
    fontSize: 14,
    fontWeight: "600",
  },
  weatherDescription: {
    fontSize: 20,
    textAlign: "center",
    fontWeight: "600",
    letterSpacing: 0.5,
    marginTop: 8,
  },
  hourlySection: {
    marginBottom: 28,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingHorizontal: 4,
    flexWrap: "wrap",
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: 0.5,
    marginLeft: 10,
    marginRight: "auto",
  },
  sectionSubtitle: {
    fontSize: 14,
    fontWeight: "400",
    marginLeft: 10,
  },
  seeAllButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: "600",
  },
  hourlyContainer: {
    borderRadius: 24,
    paddingVertical: 16,
    borderWidth: 1,
  },
  hourlyScroll: {
    marginHorizontal: -4,
  },
  hourlyScrollContent: {
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  hourlyCard: {
    width: 84,
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 12,
    marginRight: 4,
    borderRadius: 16,
    borderWidth: 1,
  },
  hourlyTime: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
  },
  rainIndicator: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    marginBottom: 4,
  },
  rainPercentage: {
    fontSize: 10,
    fontWeight: "600",
  },
  hourlyWeatherIcon: {
    width: 40,
    height: 40,
    marginBottom: 8,
  },
  hourlyTemp: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 4,
  },
  hourlyDetailsMini: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  hourlyDetailText: {
    fontSize: 12,
    fontWeight: "500",
  },
  detailsGrid: {
    marginBottom: 28,
  },
  detailsRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
  },
  detailCard: {
    flex: 1,
    alignItems: "center",
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
  },
  detailIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  detailValue: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: "500",
  },
  forecastSection: {
    marginBottom: 28,
  },
  forecastContainer: {
    borderRadius: 24,
    borderWidth: 1,
    overflow: "hidden",
  },
  forecastDayCard: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  forecastContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  forecastHeader: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  forecastDay: {
    fontSize: 16,
  },
  forecastDate: {
    fontSize: 14,
    fontWeight: "500",
    opacity: 0.8,
  },
  dotsMenuButton: {
    padding: 8,
  },
  forecastCenter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginHorizontal: 16,
  },
  forecastIcon: {
    width: 40,
    height: 40,
  },
  forecastTemp: {
    fontSize: 20,
    fontWeight: "700",
    minWidth: 45,
  },
  forecastFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  tempRange: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  forecastTempHigh: {
    fontSize: 14,
    fontWeight: "600",
  },
  forecastTempLow: {
    fontSize: 14,
    fontWeight: "600",
  },
  additionalInfo: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  infoCard: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
  },
  infoIconContainer: {
    marginRight: 12,
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: "500",
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 18,
    fontWeight: "700",
  },
  footer: {
    alignItems: "center",
    marginTop: 20,
  },
  watermark: {
    fontSize: 14,
    fontWeight: "400",
    marginBottom: 4,
  },
  appVersion: {
    fontSize: 12,
    fontWeight: "400",
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContainer: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 20,
    maxHeight: height * 0.85,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.1)",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
  },
  modalSubtitle: {
    fontSize: 14,
    fontWeight: "400",
    marginTop: 2,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  modalScrollView: {
    maxHeight: height * 0.6,
  },
  modalScrollContent: {
    paddingBottom: 20,
  },
  hourlyItem: {
    borderRadius: 15,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
  },
  hourlyItemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  hourlyTimeContainer: {
    alignItems: "flex-start",
  },
  rainChanceBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
    marginTop: 4,
  },
  rainChanceText: {
    fontSize: 12,
    fontWeight: "600",
  },
  hourlyTempMain: {
    alignItems: "flex-end",
  },
  hourlyFeelsLike: {
    fontSize: 12,
    marginTop: 2,
  },
  hourlyDetails: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  hourlyIcon: {
    width: 50,
    height: 50,
    marginRight: 12,
  },
  hourlyDescription: {
    fontSize: 16,
    fontWeight: "500",
    flex: 1,
    textTransform: "capitalize",
  },
  hourlyStats: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  hourlyStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  statIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  hourlyStatValue: {
    fontSize: 16,
    fontWeight: "700",
  },
  hourlyStatLabel: {
    fontSize: 12,
    fontWeight: "500",
  },
});
